# Generated by Django 2.2.2 on 2020-04-24 00:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_about_me_video'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='about_me',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
