# Generated by Django 2.2.6 on 2019-10-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_avatar',
        ),
        migrations.AddField(
            model_name='post',
            name='min_body',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
