# Generated by Django 2.2.6 on 2019-10-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0003_auto_20191030_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
        migrations.AlterField(
            model_name='post',
            name='place',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
