# Generated by Django 2.2.6 on 2019-10-31 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0005_auto_20191031_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lacilla',
            options={'verbose_name_plural': 'LaCilla'},
        ),
    ]
