# Generated by Django 2.2.6 on 2019-10-31 16:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('green', '0006_auto_20191031_1611'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Fotos_Portada',
        ),
        migrations.AlterModelOptions(
            name='fotos_portada',
            options={'verbose_name_plural': 'Fotos_Portada'},
        ),
    ]
