# Generated by Django 2.2.6 on 2019-11-01 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0013_cruz_de_maria_cueva_corcho_cuevas_del_caballero_degollada_del_sargento_doña_paca_fin_del_mundo_fuent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fotos_Portada',
        ),
    ]
