# Generated by Django 2.2.6 on 2019-11-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green', '0014_delete_fotos_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='la_cilla',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique_for_date='publish'),
        ),
    ]
