# Generated by Django 2.2.2 on 2019-11-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Usuarios',
        ),
    ]
