# Generated by Django 2.2.2 on 2019-11-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20191127_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name_plural': 'Usuarios'},
        ),
    ]
