# Generated by Django 2.2.2 on 2019-11-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20191127_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='totem',
            field=models.CharField(choices=[('orange', 'Oranges'), ('cantaloupe', 'Cantaloupes'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews')], default='orange', max_length=10),
        ),
    ]
