# Generated by Django 2.2.2 on 2019-11-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_usuarios_totem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='user',
            field=models.CharField(blank=True, help_text='Some text', max_length=10),
        ),
    ]
