# Generated by Django 2.2.2 on 2019-11-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20191128_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='user',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
