# Generated by Django 2.2.2 on 2019-11-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20191128_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='user',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
