# Generated by Django 2.2.2 on 2020-03-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20191204_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
