# Generated by Django 2.2.2 on 2020-03-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_usuarios_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
